In [1]:
import numpy as np

In [2]:
# System of non-linear equations --> 2D Newton
def f1(v):
    x=v[0]; y=v[1];
    return np.exp(x * y) + x*x + y - 1.4

def f2(v):
    x=v[0]; y=v[1];
    return x*x + y*y + x - 0.46

In [3]:
# Partial derivatives
def df1dx(v):
    x=v[0]; y=v[1];
    return y*np.exp(x * y) + 2*x

def df1dy(v):
    x=v[0]; y=v[1];
    return x*np.exp(x * y) + 1

def df2dx(v):
    x=v[0]; y=v[1];
    return 2*x + 1

def df2dy(v):
    x=v[0]; y=v[1];
    return 2*y

In [4]:
def jacobian(*args):
    n = int(np.sqrt(len(args)))
    assert(n % 1 == 0)
    J = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            J[i, j] = args[i*n + j]
    return J
    

In [5]:
x0 = 0.5
y0 = 0.4
v0 = np.array([x0, y0])
f1(v0), f2(v0)

(0.4714027581601701, 0.45)

In [6]:
J = jacobian(df1dx(v0), df1dy(v0), df2dx(v0), df2dy(v0))
print("J = \n", J)

J = 
 [[1.4885611  1.61070138]
 [2.         0.8       ]]


In [7]:
J.shape

(2, 2)

In [8]:
def twoD_Newton(x0, F, RTOL, ATOL):
    """
    2-dimensional Newton Method: 
    x0: starting vector cont. 2 elems.
    F : iteration function taking a vector of 2 elems and returning 2 function values
    
    """
    xk = x0
    i = 0
    repeat = 1
    while (repeat):
        i+=1
        print("iteration = ", i)
        
        J       = jacobian(df1dx(xk), df1dy(xk), df2dx(xk), df2dy(xk)) # Update Jacobi matrix with current xk
        Delta   = np.linalg.solve(J, -F(xk)) # Solve for the next step-vector to be taken
        print("Delta = ", Delta)
        xkplus1 = xk + Delta # 1 Step of fixed point iteration
        
        print("xk = ", xk, ", xk+1 = ", xkplus1, "\n")
        if ((np.abs(xkplus1 - xk) <= abs(xkplus1) * RTOL + ATOL)).all:
            print("Convergence to x = ", xkplus1)
            repeat = 0
            return xkplus1
        
        xk = xkplus1        
    

In [9]:
def F(x):
    return np.array([f1(x), f2(x)])

In [11]:
RTOL = 1e-6
ATOL = 1e-6
v0   = np.array([x0, y0])
twoD_Newton(v0, F, RTOL, ATOL)

iteration =  1
Delta =  [-0.17123082 -0.13442294]
xk =  [0.5 0.4] , xk+1 =  [0.32876918 0.26557706] 

Convergence to x =  [0.32876918 0.26557706]


array([0.32876918, 0.26557706])

# One 2D-Newton step "By Hand"

In [15]:
J_tilde_row2 = J[1] - J[0] * J[1,0]/J[0,0]
J_tilde_row2

array([ 0.        , -1.36410516])

In [24]:
f2_tilde = -f2(v0) - (-f1(v0)) * J[1,0]/J[0,0]
f2_tilde

0.1833670242041036

In [25]:
d2 = f2_tilde / J_tilde_row2[1]
d2

-0.1344229390504218

In [27]:
d1 = (-f1(v0) - J[0,1]*d2) / J[0,0]
d1

-0.17123082437983125

In [28]:
Delta = np.array([d1, d2])
v1 = v0 + Delta
v1

array([0.32876918, 0.26557706])