In [1]:
import numpy as np
import math

In [2]:
def trapezoidal(a, b, f, number_of_iterations):
    T_all = []
    # Iteration 0 -> T0
    h = (b - a) 
    s = 0.5 * (f(a) + f(b))
    T = h * s
    N = 0
    T_all.append(T)
    # Iteration 1 until max_iter
    for i in range(1, number_of_iterations):
        h = h / 2.0
        s = s + sum([f(a + (2*j + 1) * h) for j in range(N+1)])
        T = h * s
        N = 2*N + 1
        T_all.append(T)
    return T_all
        

In [62]:
def romberg(a, b, f, RTOL, ATOL):
    cols   = 2
    repeat = 1
    while(repeat):
        rows = cols
        R = np.zeros((rows, cols))
        R[:, 0] = trapezoidal(a, b, f, rows) # Compute 1st column of Romberg scheme: Ti for row i=0, 1, ..., imax
        for k in range(1, cols):
            for i in range(k, rows):
                R[i, k] = ( R[i, k-1] - 4**(-k) * R[i-1, k-1] ) / ( 1 - 4**(-k)) # Compute the other cols by combining results from the respective previous col
        print("\nR for imax = ", cols, ":\n", R)

        # Check if tolerance met and return if that's the case
        if (abs(R[-1, -1] - R[-2, -2]) <= abs(R[-1, -1])*RTOL + ATOL):
            repeat = 0
            print("\nFor the given tolerance, Romberg Method converged at imax = ", cols, " \nto final approx. R = ", R[-1, -1])
            return R

        # Else if error above tolerance, repeat Richardson extrapolation with one col and 1 row more
        else:
            cols += 1

        


In [63]:
def f1(x):
    return 1 / x
def f2(x):
    return math.sin(x) / (1 + x**2)

In [64]:
a = 1
b = 2
I = np.log(2)
print("Exact I = ", I, "\n")


RTOL = 1e-5
ATOL = 1e-5
R = romberg(a, b, f1, RTOL, ATOL)
# print(R)
print("\nFinal error = ", abs(I - R[-1, -1]))

Exact I =  0.6931471805599453 


R for imax =  2 :
 [[0.75       0.        ]
 [0.70833333 0.69444444]]

R for imax =  3 :
 [[0.75       0.         0.        ]
 [0.70833333 0.69444444 0.        ]
 [0.69702381 0.69325397 0.6931746 ]]

R for imax =  4 :
 [[0.75       0.         0.         0.        ]
 [0.70833333 0.69444444 0.         0.        ]
 [0.69702381 0.69325397 0.6931746  0.        ]
 [0.69412185 0.69315453 0.6931479  0.69314748]]

R for imax =  5 :
 [[0.75       0.         0.         0.         0.        ]
 [0.70833333 0.69444444 0.         0.         0.        ]
 [0.69702381 0.69325397 0.6931746  0.         0.        ]
 [0.69412185 0.69315453 0.6931479  0.69314748 0.        ]
 [0.6933912  0.69314765 0.69314719 0.69314718 0.69314718]]

For the given tolerance, Romberg Method converged at imax =  5  
to final approx. R =  0.6931471819167452

Final error =  1.3567998946584225e-09


In [68]:
a = 0
b = math.pi / 2.0
I = 0.526978557614
print("Exact I = ", I, "\n")


RTOL = 1e-5
ATOL = 1e-5
R = romberg(a, b, f2, RTOL, ATOL)
# print(R)
print("\nFinal error = ", abs(I - R[-1, -1]))

Exact I =  0.526978557614 


R for imax =  2 :
 [[0.22650918 0.        ]
 [0.45673745 0.53348021]]

R for imax =  3 :
 [[0.22650918 0.         0.        ]
 [0.45673745 0.53348021 0.        ]
 [0.51050416 0.5284264  0.52808948]]

R for imax =  4 :
 [[0.22650918 0.         0.         0.        ]
 [0.45673745 0.53348021 0.         0.        ]
 [0.51050416 0.5284264  0.52808948 0.        ]
 [0.52291075 0.52704627 0.52695426 0.52693624]]

R for imax =  5 :
 [[0.22650918 0.         0.         0.         0.        ]
 [0.45673745 0.53348021 0.         0.         0.        ]
 [0.51050416 0.5284264  0.52808948 0.         0.        ]
 [0.52291075 0.52704627 0.52695426 0.52693624 0.        ]
 [0.52596453 0.52698246 0.52697821 0.52697859 0.52697875]]

R for imax =  6 :
 [[0.22650918 0.         0.         0.         0.         0.        ]
 [0.45673745 0.53348021 0.         0.         0.         0.        ]
 [0.51050416 0.5284264  0.52808948 0.         0.         0.        ]
 [0.52291075 0.52704627 0