In [1]:
import numpy as np

# Convergence criterion for iterative schemes

In [2]:
# 

In [3]:
A = np.array([[1, 1, 2], [-1, 2, 1], [0, -1 , 1]])

In [4]:
spectral_radius = max(abs(np.linalg.eigvals(A)))
print("spectral radius of A = ", spectral_radius)

spectral radius of A =  2.000000000000001


# Gauss elimination with partial pivoting

In [7]:
def get_column_max(A, column):
    (m, n) = np.shape(A)
    for i in range(n):
        A[i,column]

In [11]:
def LUP_decompose(A):
    (m, n) = np.shape(A)
    assert(m==n) # Assert that A is a square matrix
    P = np.array([i for i in range(m)]) # Store permutation matrix as integer vector P of size m containing the column indices where the permutation matrix has a 1
    
    for i in range(m):
        maxA = 0
        imax = i
        
        for k in range(i, m):
            if (abs(A[k][i]) > maxA):
                maxA = abs(A[k][i])
                imax = k
        
        if (imax != i):
            # pivoting P
            j       = P[i]
            P[i]    = P[imax]
            P[imax] = j
            
            # pivoting rows of A
            ptr     = A[i]
            A[i]    = A[imax]
            A[imax] = ptr
            
            for j in range(i+1, m):
                A[j][i] = A[j][i] / A[i][i]
                
                for k in range(i+1, m):
                    A[j][k] = A[j][k] - A[j][i] * A[i][k]
    
    return A, P
            
    
    
    
    
    

In [12]:
LUP_decompose(A)

(array([[ 1,  1,  2],
        [-1,  2,  1],
        [ 0, -1,  1]]), array([0, 1, 2]))

In [215]:
def lu_factor(A):
    """
        LU factorization with partial pivoting
        
    """
    (m, n) = np.shape(A)
    assert(m==n) # Assert that A is a square matrix
    
    P = np.arange(0, m)
    # Iterate over the columns and get for each column the index of the row with maximal value in that column
    print("\n", A)
    print("\n P =", P)
    
    # Partial pivoting
    for k in range(m-1): # only iterate until m-1 because in last column nothing more to compare (all other rows already used as pivots)
       
        # Get index of row with largest absolute value in that column -> max_row_index 
        # Start comparing from row k on, because row k-1 already used as pivot in prevoius iteration. 
        # Add k because comparing within a subarray starting from row k.
        max_row_index = np.argmax(abs(A[k:n,k])) + k 
        print("\n column k = ", k, ", max_row_index = ", max_row_index)
        # Swap entries in pivoting vector: assign current max_row_index to entry for current column and move the index of the row that is replaced, to the entry where the pivot prevously was.
        P[[k,max_row_index]] = P[[max_row_index,k]]
        print("\n P = ", P)
        # Swap the rows in A such that the pivoting row moves upwards 
        A[[k,max_row_index]] = A[[max_row_index,k]]
        print("\n", A)
        
        
        # Partial pivoting done!
        
    # LU decomposition
    tmp = A
    U = np.zeros([m, m])
    U[0] = A[0]
    L = np.eye(m) # 2D array with ones on the diagonal and zeros elsewhere
    for k in range(m):# Loop over columns
        for i in range(k+1, m): # Loop over rows starting with row k+1
            L[i,k] = float(tmp[i,k] / tmp[k,k])
            print("l", i, k, " = ", L[i,k])
            for j in range(k+1, m):
                tmp[i,j] = tmp[i,j] - L[i,k] * tmp[k,j]
            print("tmp = \n", tmp)
                
    for i in range(m):
        for j in range(i+1,m):
            U[i,j] = tmp[i,j]

    print("\n")        
    print("L = \n", L)
    print("\n")
    print("U \n= ", U)


In [216]:
# a = np.array([[1, 2, 3], [-1, 4, 1], [5, -1 , 1]])

In [217]:
a = np.array([[1,1,1], [0.5,1.0,0.8], [0.25,0.5,1]])
a

array([[1.  , 1.  , 1.  ],
       [0.5 , 1.  , 0.8 ],
       [0.25, 0.5 , 1.  ]])

In [218]:
lu_factor(a)


 [[1.   1.   1.  ]
 [0.5  1.   0.8 ]
 [0.25 0.5  1.  ]]

 P = [0 1 2]

 column k =  0 , max_row_index =  0

 P =  [0 1 2]

 [[1.   1.   1.  ]
 [0.5  1.   0.8 ]
 [0.25 0.5  1.  ]]

 column k =  1 , max_row_index =  1

 P =  [0 1 2]

 [[1.   1.   1.  ]
 [0.5  1.   0.8 ]
 [0.25 0.5  1.  ]]
l 1 0  =  0.5
tmp = 
 [[1.   1.   1.  ]
 [0.5  0.5  0.3 ]
 [0.25 0.5  1.  ]]
l 2 0  =  0.25
tmp = 
 [[1.   1.   1.  ]
 [0.5  0.5  0.3 ]
 [0.25 0.25 0.75]]
l 2 1  =  0.5
tmp = 
 [[1.   1.   1.  ]
 [0.5  0.5  0.3 ]
 [0.25 0.25 0.6 ]]


L = 
 [[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.5  1.  ]]


U 
=  [[1.  1.  1. ]
 [0.  0.  0.3]
 [0.  0.  0. ]]


In [214]:
from scipy import linalg
p, l, u = linalg.lu(a)
print("P = \n", p)        
print("\nL = \n", l)
print("\nU \n= ", u)

P = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

L = 
 [[1.   0.   0.  ]
 [0.5  1.   0.  ]
 [0.25 0.   1.  ]]

U 
=  [[ 1.    1.    1.  ]
 [ 0.    0.   -0.2 ]
 [ 0.    0.    0.35]]


In [211]:
def lu_factor(A):
    """
        LU factorization with partial pivoting
        
    """
    (m, n) = np.shape(A)
    assert(m==n) # Assert that A is a square matrix
    
    P = np.arange(0, m)
    # Iterate over the columns and get for each column the index of the row with maximal value in that column
    for k in range(m):
        
        # Pivoting
        max_row_index = np.argmax(abs(A[:, k]))
        print(max_row_index + 1)
        P = 

SyntaxError: invalid syntax (<ipython-input-211-c71e8758ac36>, line 16)